# Numpy

In [2]:
import numpy as np

In [3]:
np?

## Numpy 基本属性

In [100]:
import numpy as np

array = np.array([[[1,2,3], # 定义数组
                 [2,3,4]]])
print(array)
print('dimension:', array.ndim) # 维数 
print('shape:', array.shape)
print('size:', array.size)
print('dtype:', array.dtype) # 默认整形

[[[1 2 3]
  [2 3 4]]]
dimension: 3
shape: (1, 2, 3)
size: 6
dtype: int32


## Numpy 创建 array

### 使用列表创建 向量 & 矩阵

In [25]:
import numpy as np

a = np.array([2,3,4], dtype=np.int) 
print(a) # 输出无逗号
print(a.dtype)

[2 3 4]
int32


In [18]:
matrix = np.array([[1,2,3],
             [2,3,4]])
print(matrix)

[[1 2 3]
 [2 3 4]]


### 创建 0，1，空，单位 矩阵

In [19]:
zeros = np.zeros((3,4)) # shape use()
print(zeros) # default dtype = float64

ones = np.ones((3,4), dtype=int)
print(ones)

empty = np.empty((4,5))
print(empty)

eye = np.eye(4)
print(eye)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[2.14321575e-312 2.35541533e-312 6.79038654e-313 6.79038653e-313
  2.37663529e-312]
 [2.58883487e-312 2.41907520e-312 2.44029516e-312 8.48798317e-313
  9.33678148e-313]
 [8.70018275e-313 6.79038653e-313 6.79038653e-313 2.20687562e-312
  2.37663529e-312]
 [6.79038654e-313 2.44029516e-312 8.48798317e-313 6.79107954e-144
  1.50008929e+248]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### 创建 有序矩阵

In [33]:
import numpy as np

a = np.arange(12).reshape((3,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [35]:
a = np.arange(20,50,4) # [20,50) step=4
print(a)

[20 24 28 32 36 40 44 48]


In [32]:
a = np.linspace(1,10,20).reshape((2,2,5)) # [1,10) slip as 20 pieces
print(a)

[[[ 1.          1.47368421  1.94736842  2.42105263  2.89473684]
  [ 3.36842105  3.84210526  4.31578947  4.78947368  5.26315789]]

 [[ 5.73684211  6.21052632  6.68421053  7.15789474  7.63157895]
  [ 8.10526316  8.57894737  9.05263158  9.52631579 10.        ]]]


### 创建 随机矩阵

In [5]:
np.random.random((3,4)) # [0, 1) random number

array([[0.60190358, 0.41113143, 0.56172133, 0.19182769],
       [0.36873054, 0.57158328, 0.68996113, 0.24335078],
       [0.64756199, 0.42113546, 0.8020851 , 0.14263529]])

In [9]:
np.random.randint(1, 9, (3,3)) # [1, 9) random number

array([[4, 2, 3],
       [3, 1, 8],
       [6, 4, 2]])

## Numpy 基础运算

### 算数运算

In [50]:
import numpy as np

a = np.array([10,20,30,40])
b = np.arange(4)

print(a)
print(b)

[10 20 30 40]
[0 1 2 3]


In [46]:
c = a-b # must be the same shape, then each one do it
print(c)

[10 19 28 37]


In [47]:
c = b**2 # square
print(c)

[0 1 4 9]


In [48]:
c = 10*np.sin(a) # Arc system
print(c)

[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


In [49]:
c = b<3
print(c)

[ True  True  True False]


### 矩阵运算

In [52]:
import numpy as np

a = np.array([10,20,30,40,50,60]).reshape(3,2)
b = np.arange(10).reshape(2,5)

print(a)
print(b)

[[10 20]
 [30 40]
 [50 60]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [53]:
c = np.dot(a,b) # first's column == second's row
print(c) # result first's row * second's column

[[100 130 160 190 220]
 [200 270 340 410 480]
 [300 410 520 630 740]]


### sum min max mean median

1. astype(int) 改变数据类型
2. axis=0 对于列计算 垂直操作；axis=1 对于行计算 水平操作

In [89]:
import numpy as np

a = (10*np.sin(np.random.random((3,4)))).astype(int) 

print(a)
print('sum:', np.sum(a))

[[6 8 6 7]
 [5 3 6 7]
 [5 1 6 1]]
sum: 61


In [90]:
print('sum in column:', np.sum(a, axis=0))
print('sum in row:', np.sum(a, axis=1))

sum in column: [16 12 18 15]
sum in row: [27 21 13]


In [27]:
print('min:', np.min(a))
print('max:', np.max(a))

min: 1
max: 8


In [32]:
print('mean:',np.mean(a)) # 平均值
print('median:',np.median(a)) # 中位数

mean: 5.25
median: 5.0


### cumsum diff clip

In [40]:
print('cumsum:',np.cumsum(a)) # 累加数列

cumsum: [ 5  8 15 20 28 33 41 45 48 49 55 63]


In [39]:
print('diff:\n',np.diff(a)) # 邻差数列（后-前）

diff:
 [[-2  4 -2]
 [-3  3 -4]
 [-2  5  2]]


In [48]:
print('clip 5-9 :\n',np.clip(a,5,9)) # 门槛同化

clip 5-9 :
 [[5 5 7 5]
 [8 5 8 5]
 [5 5 6 8]]


### sort transpose

In [45]:
print('sort:\n',np.sort(a)) # 排序(逐行升序)

sort:
 [[3 5 5 7]
 [4 5 8 8]
 [1 3 6 8]]


In [46]:
print('transpose:\n',np.transpose(a)) # 转置

transpose:
 [[5 8 3]
 [3 5 1]
 [7 8 6]
 [5 4 8]]


### 指定数索引

In [58]:
import numpy as np

a = (10*np.sin(np.random.random((3,4)))).astype(int)
print(a)
print('a[1][2]:',a[1][2]) # 索引从0开始
print('a[1]:',a[1,:]) # 第2行所有数 ：表示所有

[[8 5 4 6]
 [7 4 0 2]
 [1 4 4 3]]
a[1][2]: 0
a[1]: [7 4 0 2]
a[1]: [7 4 0 2]


In [56]:
print('argmin:',np.argmin(a))
print('argmax:',np.argmax(a))

argmin: 5
argmax: 0


### 迭代行，列，所有元素

In [62]:
import numpy as np

a = (10*np.sin(np.random.random((3,4)))).astype(int)
for row in a: # 迭代行
    print(row)
    
for column in a.T: # 转置即迭代列
    print(column)
    
for item in a.flat: # 把a拍平
    print(item,end=' ')

[8 5 4 6]
[7 4 0 2]
[1 4 4 3]
[8 7 1]
[5 4 4]
[4 0 4]
[6 2 3]
8 5 4 6 7 4 0 2 1 4 4 3 

## 合并，拆分ndarray

In [83]:
import numpy as np

a = np.array([1,1,1])
b = np.array([2,2,2])

print('vastack:\n',np.vstack((a,b))) # 垂直合并 vertical
print('hastack:\n',np.hstack((a,b))) # 水平合并 horizontal

vastack:
 [[1 1 1]
 [2 2 2]]
hastack:
 [1 1 1 2 2 2]


In [21]:
import numpy as np

a = np.arange(12).reshape(3,4)
print(a)

print(np.split(a,3,axis=0)) # 垂直分割 （分割线垂直移动）
print(np.vsplit(a,3))

print(np.split(a,4,axis=1)) # 水平分割
print(np.hsplit(a,4))

print(np.array_split(a,3,axis=1)) # 不等量分割 （按列求和）

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
[array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


## 变形

In [24]:
a = np.arange(12).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
a.flat # 迭代器

In [26]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
a.reshape((4,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
a = np.array([1,1,1,1])
a

array([1, 1, 1, 1])

In [29]:
a.T

array([1, 1, 1, 1])

In [30]:
a[:, np.newaxis]

array([[1],
       [1],
       [1],
       [1]])

In [32]:
a[np.newaxis, :]

array([[1, 1, 1, 1]])

## Numpy 复制

1. python面向对象，赋值->同对象，变化关联
2. 复制->只赋值不关联对象

In [101]:
import numpy as np

a = np.arange(4)
b = a.copy()
b[2] = 1

print(a)

[0 1 2 3]
